apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb
spec:
  selector:
    component: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP